version: '3'

networks:
  cboard:
    driver: bridge

services:
  mongodb:
    image: mongo
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - dbvol:/data/db
    networks:
      - cboard

  cboard-api:
    image: cboard-api
    restart: on-failure
    ports:
      - "80:80"
    environment:
      - PORT=80
      - MONGO_URL=mongodb://mongodb/cboard-api
    networks:
      - cboard
    depends_on:
      - mongodb

volumes:
  dbvol: {}